const items = [
    {nome: "Almofada ", escolhido: true},
    {nome: "Assadeira de bolo oval ", escolhido: true},
    {nome: "Assadeira de bolo retangular", escolhido: true},
    {nome: "Batedeira 220v", escolhido: false},
    {nome: "Bule de café ", escolhido: false},
    {nome: "Caixa organizadora grande", escolhido: false},
    {nome: "Caixa organizadora grande", escolhido: false},
    {nome: "Caixa organizadora Média", escolhido: false},
    {nome: "Caixa organizadora Média", escolhido: false},
    {nome: "Caneca", escolhido: false},
    {nome: "Capas de almofadas", escolhido: false},
    {nome: "Cesto para roupas ", escolhido: false},
    {nome: "Cobertor ", escolhido: false},
    {nome: "Cobre leito queen", escolhido: false},
    {nome: "Cobre leito queen", escolhido: false},
    {nome: "Conjunto de pote de plástico ", escolhido: false},
    {nome: "Cortina de cozinha ", escolhido: false},
    {nome: "Cortina de lavanderia ", escolhido: false},
    {nome: "Cortina de quarto ", escolhido: false},
    {nome: "Cortina de sala ", escolhido: false},
    {nome: "Descanso de panela ", escolhido: false},
    {nome: "Edredom ", escolhido: false},
    {nome: "Escorredor de macarrão", escolhido: false},
    {nome: "Espremedor de laranja 220v", escolhido: false},
    {nome: "Filtro de água", escolhido: false},
    {nome: "Forma de silicone ", escolhido: false},
    {nome: "Forma redonda", escolhido: false},
    {nome: "Forma retangular ", escolhido: false},
    {nome: "Frigideira ", escolhido: false},
    {nome: "Fritadeira eletrica", escolhido: false},
    {nome: "Garrada d`água", escolhido: false},
    {nome: "Garrada térmica ", escolhido: false},
    {nome: "Jarra de suco", escolhido: false},
    {nome: "Jogo americano ", escolhido: false},
    {nome: "Jogo de copo", escolhido: false},
    {nome: "Jogo de facas", escolhido: false},
    {nome: "Jogo de Prato de sobremesa ", escolhido: false},
    {nome: "Jogo de talher", escolhido: false},
    {nome: "Jogo de Xícara de café", escolhido: false},
    {nome: "Jogo de Xícara de chá", escolhido: false},
    {nome: "Jogo taça de sobremesa ", escolhido: false},
    {nome: "Kit de talher para servir silicone", escolhido: false},
    {nome: "Leiteira ", escolhido: false},
    {nome: "Lençol de cama queen ", escolhido: false},
    {nome: "Lençol de cama queen ", escolhido: false},
    {nome: "Liquidificador 220v", escolhido: false},
    {nome: "Marinex grande", escolhido: false},
    {nome: "Marinex média", escolhido: false},
    {nome: "Mixer 220v", escolhido: false},
    {nome: "Panela de arroz 220v", escolhido: false},
    {nome: "Panela de pressão ", escolhido: false},
    {nome: "Panela Grande ", escolhido: false},
    {nome: "Panela Média ", escolhido: false},
    {nome: "Panela pequena ", escolhido: false},
    {nome: "Pano de prato ", escolhido: false},
    {nome: "Pegador de macarrão ", escolhido: false},
    {nome: "Porta Guardanapo ", escolhido: false},
    {nome: "Potes de plástico ", escolhido: false},
    {nome: "Potes de Vidro ", escolhido: false},
    {nome: "Prateleira branca 1,20", escolhido: false},
    {nome: "Prato fundo", escolhido: false},
    {nome: "Prato raso", escolhido: false},
    {nome: "Processador de alimentos 220v", escolhido: false},
    {nome: "Saladeira", escolhido: false},
    {nome: "Saleiro", escolhido: false},
    {nome: "Tapete de banheiro ", escolhido: false},
    {nome: "Tapete de cozinha ", escolhido: false},
    {nome: "Tapete de quarto", escolhido: false},
    {nome: "Tapete de sala ", escolhido: false},
    {nome: "Toalha de banho/rosto", escolhido: false},
    {nome: "Toalha de mesa", escolhido: false},
    {nome: "Travessa de vidro ", escolhido: false},
    {nome: "Varal de teto ", escolhido: false},
    {nome: "Petisqueira ", escolhido: false},
    {nome: "Vaso de Planta ", escolhido: false},
    {nome: "Saca Rolha ", escolhido: false},
]

module.exports = items